@url=http://localhost:3000

### Traer todas las tareas
GET {{url}}/tareas

### Trear tarea con id
GET {{url}}/tareas/1

### Crear tareas
POST {{url}}/tareas
Content-Type: application/json

{
    "nombre": "Mantenimiento de PC",
    "completada": true
}

### Modificar tarea
PUT {{url}}/tareas/1
Content-Type: application/json

{
    "nombre": "Lavar platos restaurantes",
    "completada": true
}

### Borrar tarea de la tabla
DELETE {{url}}/tareas/5