@url=http://localhost:3000

### Traer todas las tareas
GET {{url}}/tareas

### Trear tarea con id
GET {{url}}/tareas/1

### Crear tareas
POST {{url}}/tareas
Content-Type: application/json

{
    "nombre": "Hacer",
    "completada": true
}

### Modificar tarea
PUT {{url}}/tareas/10
Content-Type: application/json

{
    "nombre": "Lavar_platos",
    "completada": false
}

### Borrar tarea de la tabla
DELETE {{url}}/tareas/4